2024-11-18 10:58:27,257 - ERROR - An unexpected e occurred: ('KeyError', '"Input to ChatPromptTemplate is missing variables {\'text\'}.  Expected: [\'image_description\', \'text\'] Received: [\'image_description\', \'query\']\\nNote: if you intended {text} to be part of the string and not a variable, please escape it with double curly braces like: \'{{text}}\'.\\nFor troubleshooting, visit: https://python.langchain.com/docs/troubleshooting/errors/INVALID_PROMPT_INPUT"')
2024-11-18 11:17:24,086 - ERROR - Error processing image: Error code: 400 - {'error': {'message': "You uploaded an unsupported image. Please make sure your image has of one the following formats: ['png', 'jpeg', 'gif', 'webp'].", 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_image_format'}}
2024-11-18 11:17:24,086 - ERROR - Error processing image: Error code: 400 - {'error': {'message': "You uploaded an unsupported image. Please make sure your image has of one the following formats: ['png', 'jpeg', 'gif', 'webp'].", 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_image_format'}}
2024-11-18 12:15:14,814 - ERROR - An unexpected e occurred: ('AttributeError', "'QueryResponse' object has no attribute 'alert'")
2024-11-18 12:15:14,814 - ERROR - An unexpected e occurred: ('AttributeError', "'QueryResponse' object has no attribute 'alert'")
2024-11-18 13:10:41,412 - ERROR - Error processing image: Error code: 400 - {'error': {'message': "You uploaded an unsupported image. Please make sure your image has of one the following formats: ['png', 'jpeg', 'gif', 'webp'].", 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_image_format'}}
2024-11-18 13:10:41,412 - ERROR - Error processing image: Error code: 400 - {'error': {'message': "You uploaded an unsupported image. Please make sure your image has of one the following formats: ['png', 'jpeg', 'gif', 'webp'].", 'type': 'invalid_request_error', 'param': None, 'code': 'invalid_image_format'}}
2024-11-18 13:13:10,426 - ERROR - An unexpected e occurred: ('ValidationError', "2 validation errors for QueryResponse\nanswer\n  Field required [type=missing, input_value={'related_queries': None}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing\nrelated_queries\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.9/v/list_type")
2024-11-18 13:13:10,426 - ERROR - An unexpected e occurred: ('ValidationError', "2 validation errors for QueryResponse\nanswer\n  Field required [type=missing, input_value={'related_queries': None}, input_type=dict]\n    For further information visit https://errors.pydantic.dev/2.9/v/missing\nrelated_queries\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.9/v/list_type")
2024-11-18 13:15:34,553 - ERROR - An unexpected e occurred: ('ValidationError', '1 validation error for QueryResponse\nrelated_queries\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.9/v/list_type')
2024-11-18 13:15:34,553 - ERROR - An unexpected e occurred: ('ValidationError', '1 validation error for QueryResponse\nrelated_queries\n  Input should be a valid list [type=list_type, input_value=None, input_type=NoneType]\n    For further information visit https://errors.pydantic.dev/2.9/v/list_type')
2024-11-18 13:23:10,796 - ERROR - An unexpected e occurred: ('ValidationError', '1 validation error for QueryResponse\nanswer\n  Input should be a valid dictionary [type=dict_type, input_value="The steps in a phishing ...ss private information.", input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/dict_type')
2024-11-18 13:23:10,796 - ERROR - An unexpected e occurred: ('ValidationError', '1 validation error for QueryResponse\nanswer\n  Input should be a valid dictionary [type=dict_type, input_value="The steps in a phishing ...ss private information.", input_type=str]\n    For further information visit https://errors.pydantic.dev/2.9/v/dict_type')
